baseurl = "https://davidpross.com/"
languageCode = "en-us"
title = "David Ross"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    weight = 1
    name = "Resume"
    url = "/resume/"

[[menu.main]]
    weight = 2
    name = "Email"
    url = "mailto:rossdavi@ohsu.edu"
    
[params]
    description = "Personal website for David Ross."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "logo.svg"
    width = 50
    height = 50
    alt = "Logo"

