baseurl: "https://davidpross.com/"
languageCode: "en-us"
title: "Personal website of David Ross."
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: Blog
      url: /blog/
      weight: 3
    - name: Resume
      url: /resume
      weight: 4

params:
  description: "A website built with Hugo."
  footer: "&copy; [David Ross](https://davidpross.com) 2025 | [![](/img/LI-In-Bug.png)](https://www.linkedin.com/in/daverossname/) [![](/img/github-mark.png)](https://github.com/davidpross)"

markup:
  goldmark:
    renderer:
      unsafe: true
