---
title: Resume
author: David Ross
slug: resume
categories: []
tags: []
---

Software developer completing a master’s degree in bioinformatics and computational biomedicine with anticipated graduation in June 2021. Strong programming skills, motivated to contribute on a technical team partnering with biologists to leverage computational tools to advance biology and biomedical research.

[Download PDF version of resume](/Ross-resume.pdf)

Key Skills
--------------------------  ----------------------- ----------------------
•	Software development      •	R                     •	Bash scripting
•	Data visualization        •	Shiny                 •	Git version control
•	Technical presentations	  •	Python                •	SQL
--------------------------  ----------------------  ----------------------

## Relevant Experience

### Biostatistics Intern — NanoString Technologies Inc. — Seattle, Washington — 2021

-	Developed interactive visualization tool for exploratory data analysis of spatial transcriptomics data.
-	Contributed to development of new data analysis pipeline for technology access program.
-	Presented interactive visualization tool to senior leadership as well as current customers.
-	Selected to attend industry conference announcing new spatial biology technologies.

### Bioinformatics Scientist Intern — Providence Cancer Center — Portland, Oregon — 2020

- Performed bioinformatics analyses to support cancer immunology research.
- Used Seurat R package to analyze scRNA-seq data from tumor-infiltrating lymphocytes.
- Created two interactive apps for data visualization and analysis of multiplex immunohistochemistry and TCR-seq data using R shiny package.
- Created visualization for scientific journal article [published](https://pubmed.ncbi.nlm.nih.gov/33820811/) in _Cancer Immunology Research_.

## Education

### Master of Science — Oregon Health & Science University — Portland, Oregon — 2021 (Anticipated)

- Major: Bioinformatics and computational biomedicine
- Related coursework: Statistics, Machine Learning, Bioinformatics Algorithms, Computational Genetics, Data Visualization

### Post-Baccalaureate — Portland State University — Portland, Oregon — 2018–2019

- Major: Biology
- Related coursework: Genetics, Molecular Biology, Cell Biology, Virology, Cancer Biology

### Massive Open Online Courses — edX.org — 2016–2018

- Related coursework: Chemistry, Biology, Differential Equations, Data Science

### Bachelor of Arts — Davidson College — Davidson, North Carolina — 1998

- Major: Economics

## Additional Experience

### Independent Software Developer — David Ross Software — Portland, Oregon — 2004–2014

- Developer of Windows, Mac and iOS apps.
- Created multiple apps for iOS platform including Uni Sudoku which was featured in the launch of the App
Store for iPad.
- Created the Knit Buddy iPhone app in partnership with _Vogue Knitting_.

### Software Developer — American Management Systems — Fairfax, Virginia — 1998–2002

- Developed market-leading financial management software sold to federal civilian agencies with up to 5000+ users.
- Technical manager in charge of release-specific enhancements and responsible for improving software development processes from design stages through implementation.
- C++ application server and Smalltalk GUI development.
- Complex data manipulation with SQL on various relational database platforms.

